# Site settings
timezone: Europe/Berlin

baseurl: '' # the subpath of your site, e.g. /blog/
url: 'http://daniellimberger.de' # the base hostname & protocol for your site

title: 'Daniel Limberger'
author: 'Daniel Limberger'

languages: [ 'en', 'de' ]

google_font_sans_serif: 'Source+Sans+Pro:300'

flickr_user: '131006004@N06'
flickr_api_key: adb4be93419edab991522b4fa92b7029

default_header_img_dimensions: 'width="1024" height="1024"'
default_thubmnail_img_dimensions: 'width="768" height="768"'

# Handling Reading
safe: true
encoding: utf-8

# Build settings
markdown: kramdown

# Outputting
exclude: [
  'cibuild',
  'Gemfile',
  'Gemfile.lock',
  'package.json',
  'README.md',
  'vendor']

defaults:
  - scope:
      path: ''
    values:
      lang: en
      description: 'Personal website of Daniel Limberger, a Berlin based Graphics Systems Engineer, Researcher, and Entrepreneur. It enlists his publications, projects, talks, teachings, and contact information.'
  - scope:
      path: 'de'
    values:
      lang: de
      description: 'Persönliche Webseite von Daniel Limberger, Ingeniuer für grafische System, Forscher und Unternehmer. Die Webseite listet Veröffentlichungen, Projekte, Vorträge, Lehrtätigkeiten und Kontaktdaten.'
  - scope:
      path: 'en'
    values:
      lang: en

# CSS Minification
sass:
  style: compressed
